[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["cd apps/web", "npm install"]

[phases.build]
cmds = ["cd apps/web && npm install && npx prisma generate && npm run build"]

[start]
cmd = "cd apps/web && npm start"
